# Define os serviços (containers) que compõem nossa aplicação
services:
  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:14-alpine
    container_name: parking_db
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker_password
      POSTGRES_DB: parking_db
    ports:
      # Mapeia a porta 5432 do container para a 5432 da sua máquina
      - "5432:5432"
    volumes:
      # Persiste os dados do banco em um volume, para não perdê-los
      # quando o container for reiniciado.
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d parking_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serviço do Back-end
  parking-api:
    build:
      context: ./parking-api # Diz para o Docker construir a partir da pasta parking-api'
      dockerfile: Dockerfile # Usando o Dockerfile que criamos lá
    container_name: parking-api
    restart: always
    ports:
      - "3333:3333"
    depends_on:
      db:
        # Garante que o backend só vai iniciar depois que o banco de dados
        # estiver saudável e pronto para receber conexões.
        condition: service_healthy
    environment:
      # Variáveis de ambiente que a aplicação usará para se conectar ao banco.
      # 'db' é o nome do serviço do banco, que o Docker resolve como o endereço de rede.
      DB_HOST: db
      DB_USER: docker
      DB_PASS: docker_password
      DB_NAME: parking_db
      APP_SECRET: ${APP_SECRET}
    volumes:
      - ./parking-api:/usr/src/app
      - /usr/src/app/node_modules  

  # Serviço do Front-end
  parking-front:
    build:
      context: ./parking-front
      dockerfile: Dockerfile
    container_name: parking-front
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - parking-api

  pgadmin: # <-- ADICIONADO
    image: dpage/pgadmin4 # <-- ADICIONADO
    container_name: parking_pgadmin # <-- ADICIONADO
    restart: always # <-- ADICIONADO
    environment: # <-- ADICIONADO
      PGADMIN_DEFAULT_EMAIL: admin@parking.com # <-- ADICIONADO
      PGADMIN_DEFAULT_PASSWORD: admin # <-- ADICIONADO
    ports: # <-- ADICIONADO
      - "8080:80" # Mapeia a porta 8080 da sua máquina para o PGAdmin # <-- ADICIONADO
    volumes: # <-- ADICIONADO
      - pgadmin_data:/var/lib/pgadmin # Persiste a configuração do PGAdmin # <-- ADICIONADO
    depends_on: # <-- ADICIONADO
      - db # Garante que o PGAdmin só inicie após o banco de dados estar pronto # <-- ADICIONADO
# Define o volume nomeado que usamos para o banco de dados
volumes:
  postgres_data:
  pgadmin_data: